### ISSUE TITLE
Error "Array to string conversion" when create with multiple data

### ISSUE THREAD

**Issue by ikkosatrio** [Astrotomic/laravel-translatable#37] opened 2019-07-31 18:35 UTC
![image](https://user-images.githubusercontent.com/17069028/62238101-7e15d000-b3fc-11e9-8527-3b74e5aaa0c2.png)

**Comment by Gummibeer** [comment] 2019-07-31 19:35
The issue is that there is an attribute and locale `id`. This was already discussed in 
https://github.com/dimsav/laravel-translatable/issues/546

Atm I have no good solution for it. And it's not on top of my own priorities because I don't need Indonesian.
But feel free to create a fix and open a PR.

The best solution I could think about would be a "conflicting attributes / locales" config. Which is used for a `$attribute in $conflicting && $value is array` check. Which would limit it to conflicting attributes which aren't an array/collection.

But feel free to find a better way if you want. 😉

**Comment by ikkosatrio** [comment] 2019-08-01 07:01
can you give me some example for "$attribute in $conflicting && $value is array check", and where i add that?
![image](https://user-images.githubusercontent.com/17069028/62272226-ce287d00-b464-11e9-8cb2-416bd9851e83.png)

**Comment by Gummibeer** [comment] 2019-08-01 08:46
@ikkosatrio the simple fix to prevent trying to fill a translation with a non-array is in #38 
I will release this later today.

**Comment by ikkosatrio** [comment] 2019-08-01 13:28
sorry, is that right? I change my code with the code below

Translatable
![image](https://user-images.githubusercontent.com/17069028/62297044-9fc59480-b49a-11e9-9f83-fc2800922ccd.png)

Model
![image](https://user-images.githubusercontent.com/17069028/62297063-abb15680-b49a-11e9-9a95-a3e3e531ae91.png)

Controller
![image](https://user-images.githubusercontent.com/17069028/62297099-bb309f80-b49a-11e9-8b9f-594746da2762.png)

**Comment by Gummibeer** [comment] 2019-08-01 13:45
If it's copied - but like I said this fix will be in an official release today.

**Closed** 2019-08-01 13:53 UTC
Labels: bug, help wanted

**Comment by Gummibeer** [comment] 2019-08-02 07:30
Sorry for the delay - it's now released
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.1.3

**Comment by ikkosatrio** [comment] 2019-08-02 15:16
thx for the update,but  when i try it,
![image](https://user-images.githubusercontent.com/17069028/62380272-1635c580-b573-11e9-8605-2439135c0edc.png)
 only save the "en" locale
![image](https://user-images.githubusercontent.com/17069028/62380322-2baaef80-b573-11e9-8db9-d9cee62f930c.png)

**Comment by Gummibeer** [comment] 2019-08-02 16:16
Have you added `id` to the locales config?

**Comment by ikkosatrio** [comment] 2019-08-03 13:00
ya, i'm already add "id"
![image](https://user-images.githubusercontent.com/17069028/62412206-5192cb80-b629-11e9-8588-d35fb48d21da.png)
